services:
  jekyll-pwg:
    image: jekyll/jekyll:latest
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    # network_mode: "host" # use for Ubuntu, possible: do not use for MacOS?
  php-bb-psql:
    image: postgres:latest
    ports:
      - 5432:5432
    # network_mode: "host" # do not use for MacOS, use for Ubuntu
    environment:
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qaswerd
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local